version: 2
jobs:
  lint-shell-scripts:
    docker:
      - image: docker:18.09-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Lint Shell Scripts
          command: |
            find generators -path '*/bin/*' | {
              while IFS= read -r file_path; do
                echo "shellcheck ${file_path}"
                docker run --rm --interactive koalaman/shellcheck:v0.6.0 -x /dev/stdin < "${file_path}"
              done
            }
  build:
    docker:
      - image: node:14.15.0

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install
      - run: npm run lint
      - run: npm run test
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  deploy:
    docker:
      - image: node:14.15.0

    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npx semantic-release

workflows:
  version: 2
  build_deploy:
    jobs:
      - build:
          context: reaction-publish-semantic-release
          requires:
            - lint-shell-scripts
      - deploy:
          context: reaction-publish-semantic-release
          requires:
            - build
          filters:
            branches:
              only: master
      - lint-shell-scripts
